kind: containerapp
location: koreasouth
name: rest-api
resourceGroup: guney-aks
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: ${MANAGED_ENV_ID}
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 8080
      transport: auto
      allowInsecure: false
    registries:
      - server: ghcr.io
        username: ${GH_ACTOR}
        passwordSecretRef: ghcr-password
    secrets:
      - name: ghcr-password
        value: ${GH_TOKEN}
  template:
    containers:
      - name: rest-api
        image: ${IMAGE_TAG}
        resources:
          cpu: 0.5
          memory: 1.0Gi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: REDIS_HOST
            value: "${REDIS_HOST}"
          - name: REDIS_PORT
            value: "${REDIS_PORT}"
          - name: REDIS_TOKEN
            value: "${REDIS_TOKEN}"
          - name: KAKAO_CLIENT_ID
            value: "${KAKAO_CLIENT_ID}"
          - name: KAKAO_CLIENT_SECRET
            value: "${KAKAO_CLIENT_SECRET}"
          - name: KAKAO_REFRESH_TOKEN
            value: "${KAKAO_REFRESH_TOKEN}"
          - name: GEMINI_API_KEY
            value: "${GEMINI_API_KEY}"
          - name: APP_ADMIN_EMAILS
            value: "${APP_ADMIN_EMAILS}"
          - name: GRAFANA_TOKEN
            value: "${GRAFANA_TOKEN}"
    scale:
      minReplicas: 2
      maxReplicas: 5
      rules:
        - name: http-scaling-rule
          http:
            metadata:
              concurrentRequests: "50"
